// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8j0N3WeMyliw_9XVOXV1M8ZJWOyfFE6Q',
    appId: '1:101750492930:web:01426836114e16140cfc1b',
    messagingSenderId: '101750492930',
    projectId: 'view-point-c281c',
    authDomain: 'view-point-c281c.firebaseapp.com',
    storageBucket: 'view-point-c281c.appspot.com',
    measurementId: 'G-Q05VDPG4CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwdYgoc-L8DG7BruVAXp0SosfLmn-dhvg',
    appId: '1:101750492930:android:d6d5e8c5196ccf7a0cfc1b',
    messagingSenderId: '101750492930',
    projectId: 'view-point-c281c',
    storageBucket: 'view-point-c281c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtXhc4t9RXVbmAspgCg7PXOEvNRxEWTA',
    appId: '1:101750492930:ios:16d6c68d9ba317800cfc1b',
    messagingSenderId: '101750492930',
    projectId: 'view-point-c281c',
    storageBucket: 'view-point-c281c.appspot.com',
    iosBundleId: 'com.example.viewPoint',
  );
}
