// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCiaCFvKsfctUDB46UizzfLjWE48UD-A',
    appId: '1:865270667482:web:0bef1ce72c9095e0c3ade3',
    messagingSenderId: '865270667482',
    projectId: 'view-point-new',
    authDomain: 'view-point-new.firebaseapp.com',
    storageBucket: 'view-point-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0QQeHOjc6CyCooh-B44WlExWnGMuDt-I',
    appId: '1:865270667482:android:b012e0cb452b9563c3ade3',
    messagingSenderId: '865270667482',
    projectId: 'view-point-new',
    storageBucket: 'view-point-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsC8EiVMOx9J-fXG2pDxvXOXk01gbLA6Q',
    appId: '1:865270667482:ios:eab0b732c11ee2a3c3ade3',
    messagingSenderId: '865270667482',
    projectId: 'view-point-new',
    storageBucket: 'view-point-new.appspot.com',
    iosBundleId: 'com.example.viewPoint',
  );

}